Add descriptive identifiers to blog post links
skydread1/flybot.sg pull request #157
Opened 2023-07-04 07:22 UTC by flybot-nam-nguyenhoai

This commit adds descriptive identifiers to blog post URLs (e.g., from `/blog/sg15y5m` to `/blog/sg15y5m/Our_Language_Clojure`), and updates existing links to use these new identifiers.

FIXME: This commit includes several new utility functions that probably need to be relocated:

- Map filtering functions in `flybot.common.utils`
- Functions for manipulating Hiccup vectors, querying posts and converting page names in `flybot.client.web.core.dom.common`

2023-07-05 03:59 UTC, skydread1 requested changes
In general we want to have as few functions as possibles in `utils`.

Same goes for the too generic `common` ns.

- There is a `hiccup` namespace already existing where you can move your hiccup related helper functions
- In the common folder, you can create `link.cljs` to add your internal-link logic
- Maybe some post related helper functions should be added in post.cljs directly or a subfolder for post.

You need to identify where your logic is needed (who requires it) and you should be able to get rid of the common.cljs namespace which is bad practice

2023-07-05 03:59 UTC, skydread1 commented on common/src/flybot/common/utils.cljc
> +    [(:require [markdown-to-hiccup.core :as mth])]))
Can be simplified like this:

```clojure
(ns flybot.common.utils
  (:require [markdown-to-hiccup.core :as mth]
            #?(:clj [datalevin.core :as d])))
```

2023-07-05 03:59 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/common.cljs
> +                                    (matches-url-identifier? post)))))]
can use `into` directly here for clarity with the arity `(into to xform from)`

```clojure
queried-posts (into
                        {}
                        (filter
                         (fn [[id post]]
                           (and (matches-id-ending? id)
                                (matches-page? post)
                                (matches-url-identifier? post))))
                        @(rf/subscribe [:subs/pattern {:app/posts '?x}]))
```

2023-07-05 03:59 UTC, skydread1 commented on common/src/flybot/common/utils.cljc
> +  (into {} (filter #(pred (val %)) map)))
unused so can remove

2023-07-05 03:59 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/common.cljs
> +   (let [matches-page? (fn [post] (or (= :all page-name)
What is the purpose of `(= :all page-name)`?

2023-07-05 05:30 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/common.cljs
> +                                    (matches-url-identifier? post)))))]
Today I learned about transducers. Thanks!

2023-07-05 05:45 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/common.cljs
> +   (let [matches-page? (fn [post] (or (= :all page-name)
I initially thought I might need it to visit a post when I wouldn't be sure what page it belonged to.

Removed.

2023-07-05 07:29 UTC, flybot-nam-nguyenhoai commented on common/src/flybot/common/utils.cljc
> +    [(:require [markdown-to-hiccup.core :as mth])]))
Reverted to only requiring `datalevin.core`.

2023-07-05 07:29 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/common.cljs
> +                                    (matches-url-identifier? post)))))]
Fixed.

2023-07-05 08:20 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +                         add-post-hiccup-content)]
good!

2023-07-05 08:24 UTC, skydread1 requested changes
Some clj tests are failing which is expected as you modified a malli schema which is used both both frontend and backend validation.

Good reflex is to run the clj locally before pushing.

2023-07-05 08:24 UTC, skydread1 commented on common/src/flybot/common/validation/markdown.cljc
> +  [^String md-content]
You don't have to type hint here.

Our type validations are all made via malli.

In general in Clojure, we use type hint as last resort for compilation optimisation for instance which we don't need in this case.

2023-07-05 08:52 UTC, flybot-nam-nguyenhoai commented on common/src/flybot/common/validation/markdown.cljc
> +  [^String md-content]
Got it. I actually don't remember why I put the type hint there.

2023-07-05 08:54 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +                         add-post-hiccup-content)]
Thank you! (I'm not sure what I did well, but thank you anyway.)

2023-07-06 04:07 UTC, flybot-nam-nguyenhoai commented
To test the new descriptive URLs, I'm thinking of doing the following:

1. `(test-fixtures)` to initialize
2. Create a new post
3. Create a descriptive link using `(post-link post)`
4. Open the link (somehow)
5. Check that the new `app-db` page contains only the new post

Steps 4 and 5 seem tricky at the moment, so any help will be greatly appreciated.

2023-07-06 05:16 UTC, skydread1 commented
> To test the new descriptive URLs, I'm thinking of doing the following:
> 
> 1. `(test-fixtures)` to initialize
> 2. Create a new post
> 3. Create a descriptive link using `(post-link post)`
> 4. Open the link (somehow)
> 5. Check that the new `app-db` page contains only the new post
> 
> Steps 4 and 5 seem tricky at the moment, so any help will be greatly appreciated.

We can focus on checking if the `:current-view` has been properly updated (it would be updated when you call `internal-link` because it will trigger the dispatch from `on-navigate`:
```clojure
(rf/dispatch [:evt.page/set-current-view new-match])
``` 

A simple test for the `apply` page (without any params) could be:
```clojure
(deftest internal-link
  (rf-test/run-test-sync
   (test-fixtures)
   (sut/internal-link :flybot/apply "Apply")
   (let [current-view (rf/subscribe [:subs/pattern
                                     {:app/current-view
                                      {:data
                                       {:name '?
                                        :page-name '?}
                                       :path-params '?}}
                                     :all])]
     (testing "Navigates to apply page."
       (is (= {:app/current-view 
               {:data {:name :flybot/home, :page-name :home}
                :path-params {}}}
            (get @current-view '&?)))))))
```

2023-07-06 09:05 UTC, flybot-nam-nguyenhoai commented on common/src/flybot/common/validation/markdown.cljc
> +  [^String md-content]
They got in the way during testing, too.

Removed.

2023-07-07 02:13 UTC, skydread1 approved these changes

2023-07-07 02:14 UTC, merged