Redirect post URLs with old or wrong titles
skydread1/flybot.sg pull request #167
Opened 2023-07-10 04:56 UTC by flybot-nam-nguyenhoai

## Closes #164

- [ ] Redirect post URLs such as `/blog/post-id/wrong_title` or `/blog/post-id/old_title` or `/blog/post-id/` (no title) to `/blog/post-id/latest_title`

2023-07-10 11:08 UTC, skydread1 commented
There is a race condition between the dispatch of the event `:evt.app/initialize` and the reitit router controller execution. The posts get populated after the controller dispatch the event `:evt.nav/redirect-post-url`.

I think there is no need for controllers (unlike what I initially thought), we can just dispatch `:evt.nav/redirect-post-url` from `blog-single-post-page`:

```clojure
(defn blog-single-post-page
  "Given the blog post identifier, returns the corresponding post in a page.
  If no matching post is found, returns some placeholder content."
  []
  (let [{query-id-ending '?id-ending
         query-url-identifier '?url-identifier}
        @(rf/subscribe [:subs/pattern
                        {:app/current-view
                         {:parameters
                          {:path
                           {:id-ending '?id-ending
                            :url-identifier '?url-identifier}}}}])
        _ (rf/dispatch [:evt.nav/redirect-post-url
                        :flybot/blog-post
                        :blog
                        query-id-ending
                        query-url-identifier])
        queried-post (-> (get-post-by-id-page :blog
                                              query-id-ending
                                              query-url-identifier)
                         vals
                         first
                         add-post-hiccup-content)]
    [...]))
```

2023-07-10 11:10 UTC, skydread1 requested changes

2023-07-10 11:10 UTC, skydread1 commented on client/common/src/flybot/client/common/db/event.cljs
> +
This logic is only relevant for the `web` frontend so it needs to be moved to `flybot.client.web.core.db.event`

2023-07-11 03:38 UTC, flybot-nam-nguyenhoai commented on client/common/src/flybot/client/common/db/event.cljs
> +
Relocated.

2023-07-11 03:56 UTC, skydread1 requested changes

2023-07-11 03:56 UTC, skydread1 commented on client/web/test/flybot/client/web/core/router_test.cljs
> +                                      sut/on-navigate))]
Here you can call the dispatch for your post redirect

```clojure
go-to-link (fn [path params] 
                        (rfe/push-state path params)
                        (rf/dispatch [:evt.nav/redirect-post-url
                                      :flybot/blog-post
                                      :blog
                                      {:id-ending params}
                                      {:url-identifier params}]))
```

Then you can call in your test:

```clojure
(testing "Link with wrong title goes to correct view:"
             (go-to-link :flybot/blog-post
                         {:id-ending "-temp-id"
                          :url-identifier "wrong_title"})
             (is (= expected-view (dissoc @get-current-view '&?))))
```

2023-07-11 04:04 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/router_test.cljs
> +                                      sut/on-navigate))]
`go-to-link` doesn't seem to work in the REPL.

2023-07-11 04:06 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/router_test.cljs
> +             (is (= expected-view (dissoc @get-current-view '&?))))))
These tests are failing: `@get-current-view` contains the wrong path parameters before the redirect, not the correct parameters after.

2023-07-11 04:06 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/router_test.cljs
> +             (is (= expected-view (dissoc @get-current-view '&?))))))))))
These tests are failing: @get-current-view contains the wrong path parameters before the redirect, not the correct parameters after.

2023-07-11 04:08 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/router_test.cljs
> +                                      sut/on-navigate))]
I think I did yesterday. Let me try again.

2023-07-11 05:44 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/router_test.cljs
> +                                      sut/on-navigate))]
It works, thank you!

2023-07-11 06:33 UTC, skydread1 requested changes

2023-07-11 06:33 UTC, skydread1 commented on client/common/src/flybot/client/common/db/fx.cljs
> + identity)
To be removed

2023-07-11 06:33 UTC, skydread1 commented on client/web/src/flybot/client/web/core/db/event.cljs
> +            [flybot.client.web.core.dom.page.post :as post]
We do not want deps to the `dom` here.

`post-url-identifier` should be moved in a more relevant ns.

2023-07-11 06:33 UTC, skydread1 commented on client/web/test/flybot/client/web/core/router_test.cljs
> +                          (print match)))]
`print` to be removed

2023-07-11 06:33 UTC, skydread1 commented on client/web/src/flybot/client/web/core/db/event.cljs
> +          :url-identifier (post/post-url-identifier queried-post)}]}))))
More compact impl:

```clojure
(when-not (or (not queried-post) (matches-url-identifier? queried-post))
       ;; Redirect on partial match
       {:fx.router/replace-state
        [(get router/redirect-name-map name)
         {:id-ending id-ending
          :url-identifier (post/post-url-identifier queried-post)}]})
```

2023-07-11 06:46 UTC, skydread1 requested changes

2023-07-11 06:46 UTC, skydread1 commented on client/web/src/flybot/client/web/core/router.cljs
> +     {:name :flybot/blog-post}]]
Good!

I suggest to use a dedicated key for the redirect instead of a mapping such as:

```clojure
["/blog/:id-ending"
    {:page-name :blog
     :view #(do
              (rf/dispatch [:evt.nav/redirect-post-url])
              (blog-single-post-page))}
    [""
     {:redirect-name :flybot/blog-post}]
    ["/"
     {:redirect-name :flybot/blog-post}]
    ["/:url-identifier"
     {:name :flybot/blog-post}]]
```

Then you won't trigger an error for same name route in reitit and you can easily access it in your event `evt.nav/redirect-post-url`:

```clojure
{:fx.router/replace-state
        [(or name redirect-name)
         ...]}
```

2023-07-11 07:13 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/db/event.cljs
> +            [flybot.client.web.core.dom.page.post :as post]
This will be tricky. `post-url-identifier` uses a post's Hiccup content to find its title.

2023-07-11 08:13 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/router.cljs
> +     {:name :flybot/blog-post}]]
I thought of it, but I need both redirected routes to also be named so that I can actually go to these routes using `replace-state` in my router tests.

This also makes `(or name redirect-name)` not work.

2023-07-11 08:25 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/router_test.cljs
> +                          (print match)))]
Removed.

2023-07-11 08:28 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/db/event.cljs
> +          :url-identifier (post/post-url-identifier queried-post)}]}))))
Fixed.

```clojure
(when (and queried-post (not (matches-url-identifier? queried-post))) …
```
to avoid double negatives.

2023-07-11 08:41 UTC, skydread1 commented on client/web/src/flybot/client/web/core/router.cljs
> +     {:name :flybot/blog-post}]]
```clojure
(rf/reg-event-fx
 :evt.nav/redirect-post-url
 (fn [{:keys [db]} [_]]
   (let [[name redirect-name page-name id-ending url-identifier]
         ((pull/qfn {:app/current-view
                     {:data
                      {:name '?name
                       :redirect-name '?redirect-name
                       :page-name '?page-name}
                      :path-params
                      {:id-ending '?id-ending
                       :url-identifier '?url-identifier}}}
                    [?name ?redirect-name ?page-name ?id-ending ?url-identifier])
          db)
         matches-page? (fn [post] (-> post :post/page (= page-name)))
         matches-id-ending? (fn [id] (str/ends-with? (str id) id-ending))
         matches-url-identifier? (fn [post]
                                   (= url-identifier
                                      (post/post-url-identifier post)))
         queried-post (->>
                       (:app/posts db)
                       (into {}
                             (filter (fn [[id post]]
                                       (and (matches-id-ending? id)
                                            (matches-page? post)))))
                       vals
                       first)]
     (when (and queried-post (not (matches-url-identifier? queried-post)))
       ;; Redirect on partial match (when everything matches except post title)
       {:fx.router/replace-state
        [(or name redirect-name)
         {:id-ending id-ending
          :url-identifier (post/post-url-identifier queried-post)}]}))))
```

2023-07-11 09:22 UTC, skydread1 requested changes
Good job!

2023-07-11 09:22 UTC, skydread1 commented on client/web/src/flybot/client/web/core/db/event.cljs
> +            [flybot.client.web.core.router :as router]
no need this deps anymore

2023-07-11 09:22 UTC, skydread1 commented on client/web/test/flybot/client/web/core/router_test.cljs
> +   [sg.flybot.pullable :as pull]))
no need these deps anymore

2023-07-11 09:35 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/db/event.cljs
> +            [flybot.client.web.core.router :as router]
Just `router`, right? I believe we still need `db.event` and `post`.

2023-07-11 09:35 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/router_test.cljs
> +   [sg.flybot.pullable :as pull]))
Removed.

2023-07-11 09:43 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/router.cljs
> +     {:name :flybot/blog-post}]]
Switched to using `:redirect-name` and rewrote tests.

2023-07-11 10:38 UTC, skydread1 approved these changes

2023-07-11 10:39 UTC, merged