Add custom post order for each page
skydread1/flybot.sg pull request #177
Opened 2023-07-14 09:16 UTC by flybot-nam-nguyenhoai

## Closes #169

- [ ] Allow pages to have their own custom post orders by adding a new `:post/default-order` field
    - [ ] Each post's position on the website is determined by its `:post/page` and `:post/default-order`. Posts with higher `:post/default-order` appear closer to the top.
    - [ ] New posts with `:post/default-order nil` are assumed to be placed at the bottom.
    - [ ] When a page has its content changed (e.g., a new, edited or removed post), all posts on this page have their `:post/default-order` updated.

2023-07-17 01:06 UTC, skydread1 requested changes

2023-07-17 01:06 UTC, skydread1 commented on server/src/flybot/server/core/handler/operation.clj
> +    posts))
Needs testing.

2023-07-17 01:06 UTC, skydread1 commented on common/src/flybot/common/validation.cljc
> +               date-field (u/mk-date))
```clojure
(assoc date-field (u/mk-date))
(dissoc :post/default-order)
```

2023-07-17 01:06 UTC, skydread1 commented on common/test/flybot/common/validation_test.cljc
> +        (is (= (assoc s/post-1 :post/default-order nil)
`dissoc`

2023-07-17 01:06 UTC, skydread1 commented on common/test/flybot/common/validation_test.cljc
> +        (is (= (assoc s/post-2 :post/default-order nil)
`dissoc`

2023-07-17 10:35 UTC, flybot-nam-nguyenhoai commented on common/test/flybot/common/validation_test.cljc
> +        (is (= (assoc s/post-1 :post/default-order nil)
Removed.

2023-07-17 10:35 UTC, flybot-nam-nguyenhoai commented on common/test/flybot/common/validation_test.cljc
> +        (is (= (assoc s/post-2 :post/default-order nil)
Removed.

2023-07-17 10:36 UTC, flybot-nam-nguyenhoai commented on common/src/flybot/common/validation.cljc
> +               date-field (u/mk-date))
Fixed.

2023-07-17 10:51 UTC, flybot-nam-nguyenhoai commented on server/src/flybot/server/core/handler/operation.clj
> +    posts))
I might have added too much testing.

2023-07-18 00:59 UTC, skydread1 requested changes

2023-07-18 00:59 UTC, skydread1 commented on server/src/flybot/server/core/handler/operation.clj
> +  [db {:post/keys [id] :as post}]
unused param

2023-07-18 00:59 UTC, skydread1 commented on server/test/flybot/server/core/handler/operation/post_order_test.clj
> +   [flybot.server.core.handler.operation.db :as db]))
- the test logic is more complex than the actual function being tested
- we are too low level in the ns tree to have prop based useful in this case
- the function is simple enough to be tested with a few `testing`

2023-07-18 02:13 UTC, skydread1 requested changes

2023-07-18 02:13 UTC, skydread1 commented on server/src/flybot/server/core/handler/operation.clj
> +  [db {:post/keys [id page] :as post} option]
- We might want to remove the deps to the `db` since it is just a sorting function.

2023-07-18 02:13 UTC, skydread1 commented on server/src/flybot/server/core/handler/operation.clj
> +                                  :post/creation-date))
Since each post will have a different post/default-order, there is no need for the `juxt`

2023-07-18 02:13 UTC, skydread1 commented on server/src/flybot/server/core/handler/operation.clj
> +  "Adjusts the default sorting order only for posts in `page`."
- function name could be `update-post-order` or `update-post-order-with`

2023-07-18 03:42 UTC, flybot-nam-nguyenhoai commented on server/test/flybot/server/core/handler/operation/post_order_test.clj
> +   [flybot.server.core.handler.operation.db :as db]))
Fully removed.

2023-07-18 03:45 UTC, flybot-nam-nguyenhoai commented on server/src/flybot/server/core/handler/operation.clj
> +                                  :post/creation-date))
Rewritten. Only `:post/default-order` is used now.

2023-07-18 03:45 UTC, flybot-nam-nguyenhoai commented on server/src/flybot/server/core/handler/operation.clj
> +  [db {:post/keys [id] :as post}]
Removed.

2023-07-18 03:47 UTC, flybot-nam-nguyenhoai commented on server/src/flybot/server/core/handler/operation.clj
> +  [db {:post/keys [id page] :as post} option]
Fixed. The first argument is now just a list of posts, not the full DB.

2023-07-19 05:48 UTC, flybot-nam-nguyenhoai commented on server/src/flybot/server/core/handler/operation.clj
> +  "Adjusts the default sorting order only for posts in `page`."
Fixed.

2023-07-19 06:18 UTC, skydread1 approved these changes

2023-07-19 06:23 UTC, merged