Add blog post sorting options for visitors
skydread1/flybot.sg pull request #201
Opened 2023-07-24 06:15 UTC by flybot-nam-nguyenhoai

## Closes #196

- [x] Allow visitors to sort blog posts by date created, date updated or title.
    The default is still sorting by date created, descending (newest first).

2023-07-24 14:34 UTC, skydread1 requested changes

2023-07-24 14:34 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/page/options.cljs
> +     [:select#blog-sorting-options
- no need `into`.
- `fieldset ` needs a `legend`

2023-07-24 14:34 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/page/options.cljs
> +       {:selected true
browser was raising a warning and using:
```clojure
:defaultValue true
```
should fix it.

2023-07-25 02:01 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     [page-post new-post]
PR #200 removed `[:h1 "New Post"]` from the temporary new post, so now the new post shouldn't have any headings. `[page-post new-post]` just results in a big plus button in edit mode, or nothing at all in read mode.

![this_pr_blog](https://github.com/skydread1/flybot.sg/assets/137136212/2826c32d-db47-4b82-b68f-4455ccadfd02)

If I use `blog-post-short` on `new-post` (like in #200), then there's a blank div between the page name and blog entries.

![pr_200_blog](https://github.com/skydread1/flybot.sg/assets/137136212/682e5de1-86d1-4920-aab4-78311bebc53c)

2023-07-25 02:12 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     [page-post new-post]
1. click the `+` to create a post
2. write a post
3. preview your post
4. observe the broken css

2023-07-25 02:14 UTC, skydread1 requested changes

2023-07-25 02:14 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/page/options.cljs
> +      {:name "Sort by"
name should be `sort-by`

2023-07-25 02:23 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     [page-post new-post]
And for the gap in the UI, just add a temp id check:

```clojure
(defn blog-post-short
  [{:post/keys [css-class id] :as post}]
  (let [post-title (web.utils/post->title post)]
    (when-not (utils/temporary-id? id)
      [:div.post.short
       {:key id
        :id id}
       [post-link post
        [:div.post-body
         {:class css-class}
         [:h2 post-title]
         [post-authors post]]]])))
````

2023-07-25 02:31 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     [page-post new-post]
With the code above, the new post button disappears in both edit mode and read mode. Fixing.

2023-07-25 03:03 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page/options.cljs
> +       {:selected true
Fixed.

Observations:

- Using either `value` or `defaultValue` works.
- `defaultValue` seems to be specific to React.
- The difference is that `value` is for "controlled elements" and `defaultValue` is for "uncontrolled elements."

2023-07-25 03:04 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page/options.cljs
> +      {:name "Sort by"
Fixed; name is now `blog-sorting-options`.

2023-07-25 03:05 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page/options.cljs
> +     [:select#blog-sorting-options
Fixed.

`(into)` was originally used with `(interpose [:br])` to insert breaks between fieldset elements. Both are now removed.

2023-07-25 03:06 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +                                        posts))
Fixed. I guess I really like `case`.

2023-07-25 03:07 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     [page-post new-post]
Restored according to PR #200.

2023-07-25 03:17 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/db/event.cljs
> +   (edn/read-string new-options)))
Should the form itself be in a new namespace called `flybot.client.common.dom.page.options`?

2023-07-25 03:36 UTC, skydread1 commented on client/web/src/flybot/client/web/core/db/event.cljs
> +   (edn/read-string new-options)))
No, the re-frame logic is the same for both platform (as mush as we can).

However, the markup differs between platforms, react native using native components.

2023-07-25 03:39 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/db/event.cljs
> +   (edn/read-string new-options)))
Ah, I misunderstood. So for this PR only the re-frame dispatch event should be moved to `common`.

I'll have to force-push, apologies.

2023-07-25 03:55 UTC, skydread1 approved these changes

2023-07-25 05:39 UTC, skydread1 approved these changes

2023-07-25 05:39 UTC, merged