Fix user data duplication on user login
skydread1/flybot.sg pull request #205
Opened 2023-07-24 08:57 UTC by flybot-nam-nguyenhoai

## Closes #202

- [x] Remove unused user information (e.g., user roles) when updating user information during login.

2023-07-24 13:26 UTC, skydread1 requested changes

2023-07-24 13:26 UTC, skydread1 commented on server/src/flybot/server/core/handler/operation.clj
>         :effects  {:db {:payload [updated-user]}}
```clojure
{:response (merge user updated-user) ;; roles expected in the response
  :effects  {:db {:payload [updated-user]}}
```

2023-07-24 13:26 UTC, skydread1 commented on server/src/flybot/server/core/init_data.clj
> +          :author (select-keys user-admin [:user/id])
```clojure
:author (:user/id user-admin)
```

2023-07-25 01:10 UTC, flybot-nam-nguyenhoai commented on server/src/flybot/server/core/handler/operation.clj
>         :effects  {:db {:payload [updated-user]}}
Fixed.

2023-07-25 01:24 UTC, skydread1 approved these changes

2023-07-25 01:25 UTC, merged