Add notifications; render as pop-ups ("toasts")
skydread1/flybot.sg pull request #226
Opened 2023-07-28 08:52 UTC by flybot-nam-nguyenhoai

## Closes #207

This pull request introduces pop-up ("toast") notifications and implements them for website errors (validation and HTTP).

Notifications will be added for successful actions (e.g., post submissions and removals) in future pull requests.

- [x] Add generic notifications (as simple data maps).
    These notify users when their actions succeed or fail, and can be delivered in different ways (e.g., as pop-ups or printed to console output).

- [x] Notify when encountering errors.
    Only validation errors and HTTP failures are notified to users.

- [x] Render notifications as pop-up banners ("toasts").

### Suggestions for future development

- Notify on successful actions.

- Make notification content user friendly.
    For example, error notifications in this PR contain plain Clojure maps of error details—they should instead contain helpful messages in natural language.

2023-07-28 08:57 UTC, flybot-nam-nguyenhoai commented on client/common/src/flybot/client/common/db/fx.cljs
> + ;; FIXME: Naming: :fx.ui/ or :fx.app/?
Name suggestions are welcome.

2023-07-28 08:57 UTC, flybot-nam-nguyenhoai commented on client/common/src/flybot/client/common/db/event.cljs
> + ;; FIXME: Naming: :evt.ui/ or :evt.app/?
Name suggestions are welcome.

2023-07-28 08:58 UTC, flybot-nam-nguyenhoai commented on resources/public/index.html
> +        <link href="/css/ReactToastify.css" rel="stylesheet" type="text/css">
Should this be loaded before or after the main CSS?

2023-07-31 01:00 UTC, skydread1 requested changes
Good.

We need to add a cljs test for the notification.

2023-07-31 01:00 UTC, skydread1 commented on client/common/src/flybot/client/common/db/event.cljs
> + ;; FIXME: Naming: :evt.ui/ or :evt.app/?
:evt.app/notify maybe?

2023-07-31 01:00 UTC, skydread1 commented on resources/public/index.html
> +        <link href="/css/ReactToastify.css" rel="stylesheet" type="text/css">
It's fine like that

2023-07-31 01:00 UTC, skydread1 commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     notifications/toast-notification-container]))
No need to call it twice, maybe we can move the component to the header?

2023-07-31 02:10 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     notifications/toast-notification-container]))
We can make notifications occupy a separate React component, e.g.,
```clojure
;; (ns flybot.client.web.core.dom)

(defn app []
  [:div
   [header-comp]
   [current-page]
   [footer-comp]
   [notification-comp]])
```

2023-07-31 02:18 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/dom/page.cljs
> +     notifications/toast-notification-container]))
Addressed.

2023-07-31 03:36 UTC, flybot-nam-nguyenhoai commented on client/common/src/flybot/client/common/db/fx.cljs
> + ;; FIXME: Naming: :fx.ui/ or :fx.app/?
Decided on `fx.ui`.

2023-07-31 03:36 UTC, flybot-nam-nguyenhoai commented on client/common/src/flybot/client/common/db/event.cljs
> + ;; FIXME: Naming: :evt.ui/ or :evt.app/?
Decided on `evt.app`.

2023-07-31 03:38 UTC, flybot-nam-nguyenhoai commented
Tests have been added for generic notifications (i.e., notifications that are in plain Clojure map form and stored in `:app/notification`).

2023-07-31 04:57 UTC, skydread1 approved these changes

2023-07-31 05:00 UTC, skydread1 requested changes

2023-07-31 05:00 UTC, skydread1 commented on client/common/src/flybot/client/common/db/event.cljs
> +       (assoc-in [:app/errors :failure-http-result] result)
We need to review obsolete error message logic

2023-07-31 05:00 UTC, skydread1 commented on client/web/test/flybot/client/web/core/db_test.cljs
> +(deftest app-notifications-test
Could have been jus a few lines replacing the whole error checks with notification ones

2023-07-31 05:36 UTC, flybot-nam-nguyenhoai commented on client/web/test/flybot/client/web/core/db_test.cljs
> +(deftest app-notifications-test
Simplified. Tests for `:app/errors` and `:app/notification` are now placed next to each other.

2023-07-31 05:36 UTC, flybot-nam-nguyenhoai commented on client/common/src/flybot/client/common/db/event.cljs
> +       (assoc-in [:app/errors :failure-http-result] result)
Will be addressed in a future PR.

2023-07-31 05:39 UTC, skydread1 approved these changes

2023-07-31 05:42 UTC, merged