Make internal links go to correct page positions
skydread1/flybot.sg pull request #240
Opened 2023-08-01 08:22 UTC by flybot-nam-nguyenhoai

## Closes #237

- [ ] Links to posts on the website now navigate to the top of the corresponding posts, using URL `#` fragments.
    - [ ] Blog post links navigate to the top of their respective blog post pages.
    - [ ] Links to posts on other pages navigate to the top of the corresponding post containers.

2023-08-01 08:23 UTC, flybot-nam-nguyenhoai commented
Here's an interesting bug: When a post link on the profile page is clicked, the new view does not automatically scroll to the correct post; the browser has to be refreshed for the link to go to the correct position.

2023-08-02 03:13 UTC, skydread1 commented
You can use a `reg-fx` to scroll to an element after the view has been rendered:

```clojure
(rf/reg-fx
 :fx.app/scroll-to
 (fn [_ _]
   (reagent/after-render #(when-let [el (.getElementById js/document "app")]
                      (.scrollIntoView el)))))
```

Then add this fx in the event:

```clojure
(rf/reg-event-fx
 :evt.page/set-current-view
 (fn [{:keys [db]} [_ new-match]]
   {:db (assoc db :app/current-view new-match)
    :fx [[:fx.app/scroll-to]]}))
```

This always go to top of the page but params can be added to provide the `dom-id` to scroll to

2023-08-02 03:49 UTC, flybot-nam-nguyenhoai commented
The above `.scrollIntoView` snippet is obtained from https://clojurians.slack.com/archives/C0620C0C8/p1619879858211700.

(Exact search phrase: `Say I want to scroll to an element after a page is rendered.`)

2023-08-02 05:16 UTC, skydread1 requested changes

2023-08-02 05:16 UTC, skydread1 commented on client/web/src/flybot/client/web/core/db/fx.cljs
> +   (reagent/after-render #(let [el (or (.getElementById js/document fragment)
the `or` is not correct, "app" case will not work.

2023-08-02 05:16 UTC, skydread1 commented on client/web/src/flybot/client/web/core/db/event.cljs
> +    :fx (when-let [fragment (:fragment new-match)]
`:fx` value can't be nil:

```
re-frame: ":fx" effect expects a seq, but was given  null
```

2023-08-02 05:31 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/db/fx.cljs
> +   (reagent/after-render #(let [el (or (.getElementById js/document fragment)
Fixed.

2023-08-02 05:31 UTC, flybot-nam-nguyenhoai commented on client/web/src/flybot/client/web/core/db/event.cljs
> +    :fx (when-let [fragment (:fragment new-match)]
Fixed.

2023-08-02 05:35 UTC, skydread1 approved these changes
Good

2023-08-02 05:38 UTC, merged